# Numpy

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [26]:
import numpy as np

In [27]:
recipes = np.loadtxt('data/minutes_n_ingredients.csv', skiprows=1, delimiter=',', dtype=np.int32)
print(recipes[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [28]:
a = recipes[:, 1:]
np.amin(a, axis=0), np.amax(a, axis=0), np.median(a, axis=0)

(array([0, 1], dtype=int32),
 array([2147483647,         39], dtype=int32),
 array([40.,  9.]))

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [29]:
p = np.quantile(recipes[:, 1], q=0.75, axis=0)
recipes[:, 1] = recipes[:, 1].clip(max=p)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [30]:
recipes[recipes[:, 1] == 0].shape[0]

479

In [31]:
np.place(recipes[:, 1], recipes[:, 1] == 0, 1)
recipes[recipes[:, 1] == 0].shape[0]

0

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [32]:
np.unique(recipes, axis=0).shape[0]

100000

In [55]:
np.unique(recipes[:, 1:3], axis=0).shape[0]

1135

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [34]:
np.asarray(np.unique(recipes[:, 2], return_counts=True)).T

array([[    1,    13],
       [    2,   926],
       [    3,  2895],
       [    4,  5515],
       [    5,  7913],
       [    6,  9376],
       [    7, 10628],
       [    8, 10951],
       [    9, 10585],
       [   10,  9591],
       [   11,  8297],
       [   12,  6605],
       [   13,  4997],
       [   14,  3663],
       [   15,  2595],
       [   16,  1767],
       [   17,  1246],
       [   18,   790],
       [   19,   573],
       [   20,   376],
       [   21,   217],
       [   22,   161],
       [   23,   105],
       [   24,    69],
       [   25,    50],
       [   26,    28],
       [   27,    16],
       [   28,    16],
       [   29,    12],
       [   30,    12],
       [   31,     3],
       [   32,     1],
       [   33,     2],
       [   34,     1],
       [   35,     3],
       [   37,     1],
       [   39,     1]])

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [57]:
less_than_5_ing = recipes[recipes[:, 2] <= 5]
less_than_5_ing

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [36]:
ing_per_min = recipes[:, 2]/recipes[:, 1]
np.max(ing_per_min)

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [37]:
top100 = np.argsort(recipes[:, 1], axis=0)[-100:]
np.mean(recipes[top100, 2])

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [38]:
index = np.random.choice(recipes.shape[0], size=10)
recipes[index]

array([[179811,     20,      9],
       [206227,     50,     12],
       [123000,     55,     11],
       [424891,     30,      3],
       [384630,     45,     13],
       [234756,     50,     11],
       [120212,     65,     11],
       [ 26799,     55,      8],
       [ 43620,     18,     13],
       [ 63865,     23,     10]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [39]:
mean_ing = np.mean(recipes[:, 2], axis=0)
recipes[recipes[:, 2] < mean_ing].shape[0]/recipes.shape[0]*100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [40]:
zeros = np.array(np.zeros((recipes.shape[0], 1)), dtype=np.int32)
simple = np.hstack((recipes, zeros))

np.place(simple[:, 3], np.logical_and(recipes[:, 1] <= 20, recipes[:, 2] <= 5), 1)
simple

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]], dtype=int32)

13. Выведите процент "простых" рецептов в датасете

In [41]:
simple[:, -1].sum()/recipes.shape[0]*100

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [42]:
short = recipes[recipes[:, 1] < 10]
medium = recipes[np.logical_and(recipes[:, 1] > 10, recipes[:, 1] < 20)]
long = recipes[recipes[:, 1] >= 20]

length = min(short.shape[0], medium.shape[0], long.shape[0])
groups = np.array([short[:length], medium[:length], long[:length]])
groups.shape

(3, 7588, 3)